- project:
    check:
      jobs:
        - "thoth-coala"
    gate:
      queue: "thoth-station/core"
      jobs:
        - "thoth-coala"
    post:
      jobs:
        - "trigger-build":
            vars:
              webhook_url: "https://paas.upshift.redhat.com/oapi/v1/namespaces/thoth-test-core/buildconfigs/osiris-observer"
    kebechet-auto-gate:
      queue: "thoth-station/core"
      jobs:
        - "thoth-coala"
